### ISSUE TITLE
Zeile 35 in Anführungszeichen

### ISSUE THREAD

**Issue by madic-creates** [iplabs/vault-cp#1]
Eventuell muss Zeile 35 mit Anführungszeichen versehen werden
Von
`copy_recursive $@`

Nach
`copy_recursive "$@"`

Ohne Anführungszeichen werden sonst Werte mit Leerzeichen potentiell verworfen bzw. können zu Folgefehlern führen

**Comment by headcr4sh** [comment]
Guter Einwand. Bisher hatte ich keine keys mit Leerzeichen kopiert. Aber sicher ist sicher! Magst du einen PR erstellen? ;-)

**Comment by headcr4sh** [comment]
Closed by #2
